/** Letters a question's choices can use. */
export type ChoiceKey = 'A' | 'B' | 'C' | 'D' | 'E';

export const CHOICE_KEYS: readonly ChoiceKey[] = ['A', 'B', 'C', 'D', 'E'];

/** Practice gives instant feedback; test times the run and grades at the end. */
export type QuizMode = 'practice' | 'test';

export interface Choice {
  key: ChoiceKey;
  /** Displayed to the student, so it is written in Turkish. */
  text: string;
}

/**
 * Question diagrams are stored as SVG. The `svg` field holds only the *contents*
 * of the <svg> element; the wrapper is generated by the Figure component.
 */
export interface Figure {
  viewBox: string;
  /** Spoken description of the diagram for screen readers (Turkish). */
  label: string;
  caption: string;
  svg: string;
}

export interface SolutionStep {
  title: string;
  detail: string;
}

export interface Question {
  id: string;
  /** Question body; each entry is rendered as its own paragraph. */
  stem: string[];
  /** The actual question sentence, usually starting with "Buna göre ...". */
  ask?: string;
  /** Facts given alongside the diagram. */
  given?: string[];
  figure?: Figure;
  /**
   * Same diagram with the construction lines the solution relies on. Shown only
   * once the question has been answered, so it never gives the method away.
   */
  solutionFigure?: Figure;
  choices: Choice[];
  answer: ChoiceKey;
  /** Shown right after answering in practice mode, on the result screen in test mode. */
  solution: SolutionStep[];
  /** Short nudge shown when the student is stuck. */
  hint: string;
  topic: string;
}

/**
 * A short run of questions — the unit is studied one module at a time so the
 * student never faces the whole bank at once, and gets the solutions for a
 * handful of questions while they are still fresh.
 */
export interface Module {
  id: string;
  order: number;
  /** Names the skill the module drills, in Turkish. */
  title: string;
  /** One line of detail shown under the title on the unit page. */
  summary: string;
  questions: Question[];
}

export interface Unit {
  id: string;
  order: number;
  title: string;
  subtitle: string;
  description: string;
  modules: Module[];
}

/** A student's best result for one module in one mode. */
export interface ModuleRecord {
  bestCorrect: number;
  total: number;
  attempts: number;
  lastPlayedAt: number;
  /** Best time in seconds; only meaningful in test mode. */
  bestSeconds?: number;
}
